In [ ]:
import pandas as pd
import numpy as np
import re

In [94]:
df = pd.read_csv('overview.csv')

In [95]:
df.head(50)

,Year,Host,Winner,Score,Runner-up,Number of teams
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Winners,Score,Runners-up,NaN
2,1960,France,Soviet Union,2–1 (a.e.t.),Yugoslavia,4.0
3,1964,Spain,Spain,2–1,Soviet Union,4.0
4,1968,Italy,Italy,1–1 (a.e.t.)2–0 (replay),Yugoslavia,4.0
5,1972,Belgium,West Germany,3–0,Soviet Union,4.0
6,1976,Yugoslavia,Czechoslovakia,2–2 (a.e.t.)(5–3 p),West Germany,4.0
7,1980,Italy,West Germany,2–1,Belgium,8.0
8,1984,France,France,2–0,Spain,8.0
9,1988,West Germany,Netherlands,2–0,Soviet Union,8.0
10,1992,Sweden,Denmark,2–0,Germany,8.0
11,1996,England,Germany,2–1 (g.g.),Czech Republic,16.0
12,2000,Belgium Netherlands,France,2–1 (g.g.),Italy,16.0
13,2004,Portugal,Greece,1–0,Portugal,16.0
14,2008,Austria Switzerland,Spain,1–0,Germany,16.0
15,2012,Poland Ukraine,Spain,4–0,Italy,16.0
16,2016,France,Portugal,1–0 (a.e.t.),France,24.0
17,2020[c],Europe[d],Italy,1–1 (a.e.t.)(3–2 p),England,24.0
18,2024,Germany,Spain,2–1,England,24.0
19,2028,England Northern Ireland Republic of Ireland...,NaN,NaN,NaN,24.0
20,2032,Italy Turkey,NaN,NaN,NaN,24.0

In [96]:
df.dtypes

Year                object
Host                object
Winner              object
Score               object
Runner-up           object
Number of teams    float64
dtype: object

In [97]:
df = df.dropna(subset=['Year',"Winner"])

In [98]:
df.reset_index(drop=True, inplace=True)

In [99]:
df = df.astype(str).map(lambda x: x.strip().upper())
df.head(50)

,Year,Host,Winner,Score,Runner-up,Number of teams
0,1960,FRANCE,SOVIET UNION,2–1 (A.E.T.),YUGOSLAVIA,4.0
1,1964,SPAIN,SPAIN,2–1,SOVIET UNION,4.0
2,1968,ITALY,ITALY,1–1 (A.E.T.)2–0 (REPLAY),YUGOSLAVIA,4.0
3,1972,BELGIUM,WEST GERMANY,3–0,SOVIET UNION,4.0
4,1976,YUGOSLAVIA,CZECHOSLOVAKIA,2–2 (A.E.T.)(5–3 P),WEST GERMANY,4.0
5,1980,ITALY,WEST GERMANY,2–1,BELGIUM,8.0
6,1984,FRANCE,FRANCE,2–0,SPAIN,8.0
7,1988,WEST GERMANY,NETHERLANDS,2–0,SOVIET UNION,8.0
8,1992,SWEDEN,DENMARK,2–0,GERMANY,8.0
9,1996,ENGLAND,GERMANY,2–1 (G.G.),CZECH REPUBLIC,16.0
10,2000,BELGIUM NETHERLANDS,FRANCE,2–1 (G.G.),ITALY,16.0
11,2004,PORTUGAL,GREECE,1–0,PORTUGAL,16.0
12,2008,AUSTRIA SWITZERLAND,SPAIN,1–0,GERMANY,16.0
13,2012,POLAND UKRAINE,SPAIN,4–0,ITALY,16.0
14,2016,FRANCE,PORTUGAL,1–0 (A.E.T.),FRANCE,24.0
15,2020[C],EUROPE[D],ITALY,1–1 (A.E.T.)(3–2 P),ENGLAND,24.0
16,2024,GERMANY,SPAIN,2–1,ENGLAND,24.0

In [100]:
df['Year'] = df['Year'].astype(str).apply(lambda x: x[0:4])

In [101]:
df['Host'] = df['Host'].astype(str).apply(lambda x: x.split('[')[0])

In [102]:
def clean_score_and_extract_hints(score):
    hints = re.findall(r'\((.*?)\)', score)
    scores = re.findall(r'(\d+–\d+)', score)
    score_hint_pairs = []
    for idx, s in enumerate(scores):
        related_hint = hints[idx] if idx < len(hints) else "Full Time"
        score_hint_pairs.append((s, related_hint))
    return score_hint_pairs
    
df['Score'] = df['Score'].apply(clean_score_and_extract_hints)

In [103]:
df.head(50)

,Year,Host,Winner,Score,Runner-up,Number of teams
0,1960,FRANCE,SOVIET UNION,"[(2–1, A.E.T.)]",YUGOSLAVIA,4.0
1,1964,SPAIN,SPAIN,"[(2–1, Full Time)]",SOVIET UNION,4.0
2,1968,ITALY,ITALY,"[(1–1, A.E.T.), (2–0, REPLAY)]",YUGOSLAVIA,4.0
3,1972,BELGIUM,WEST GERMANY,"[(3–0, Full Time)]",SOVIET UNION,4.0
4,1976,YUGOSLAVIA,CZECHOSLOVAKIA,"[(2–2, A.E.T.), (5–3, 5–3 P)]",WEST GERMANY,4.0
5,1980,ITALY,WEST GERMANY,"[(2–1, Full Time)]",BELGIUM,8.0
6,1984,FRANCE,FRANCE,"[(2–0, Full Time)]",SPAIN,8.0
7,1988,WEST GERMANY,NETHERLANDS,"[(2–0, Full Time)]",SOVIET UNION,8.0
8,1992,SWEDEN,DENMARK,"[(2–0, Full Time)]",GERMANY,8.0
9,1996,ENGLAND,GERMANY,"[(2–1, G.G.)]",CZECH REPUBLIC,16.0
10,2000,BELGIUM NETHERLANDS,FRANCE,"[(2–1, G.G.)]",ITALY,16.0
11,2004,PORTUGAL,GREECE,"[(1–0, Full Time)]",PORTUGAL,16.0
12,2008,AUSTRIA SWITZERLAND,SPAIN,"[(1–0, Full Time)]",GERMANY,16.0
13,2012,POLAND UKRAINE,SPAIN,"[(4–0, Full Time)]",ITALY,16.0
14,2016,FRANCE,PORTUGAL,"[(1–0, A.E.T.)]",FRANCE,24.0
15,2020,EUROPE,ITALY,"[(1–1, A.E.T.), (3–2, 3–2 P)]",ENGLAND,24.0
16,2024,GERMANY,SPAIN,"[(2–1, Full Time)]",ENGLAND,24.0

In [104]:
df['Score'] = df['Score'].astype(str).apply(lambda x: re.sub(r"[()\[\]{}]", "", x))
df.Score

0                      '2–1', 'A.E.T.'
1                   '2–1', 'Full Time'
2     '1–1', 'A.E.T.', '2–0', 'REPLAY'
3                   '3–0', 'Full Time'
4      '2–2', 'A.E.T.', '5–3', '5–3 P'
5                   '2–1', 'Full Time'
6                   '2–0', 'Full Time'
7                   '2–0', 'Full Time'
8                   '2–0', 'Full Time'
9                        '2–1', 'G.G.'
10                       '2–1', 'G.G.'
11                  '1–0', 'Full Time'
12                  '1–0', 'Full Time'
13                  '4–0', 'Full Time'
14                     '1–0', 'A.E.T.'
15     '1–1', 'A.E.T.', '3–2', '3–2 P'
16                  '2–1', 'Full Time'
Name: Score, dtype: object

In [105]:

def extract_first_score_and_ordered_hints(row):
    parts = row.replace(' ', '').replace("'","").split(",")
   
    main_score = parts[0]
    
    normal_hints = []
    penalty_hints = []
    replay_hints = []
    
    for  part in parts[1:]:
      
        if 'replay' in part:  
            replay_hints.append(part.upper())
            
        elif part[-1] == 'P':
            penalty_hints.append(part.replace('P', ' PENALTIES'))  
            normal_hints = normal_hints[:-1]
            
            
        else:
            normal_hints.append(part.upper())  
        
    ordered_hints = normal_hints + replay_hints + penalty_hints
    hints_str = " , ".join(ordered_hints) if ordered_hints else None

    return pd.Series([main_score, hints_str])
df[['Score', 'Hints']] = df['Score'].astype(str).apply(extract_first_score_and_ordered_hints)

In [106]:
df.head(50)

,Year,Host,Winner,Score,Runner-up,Number of teams,Hints
0,1960,FRANCE,SOVIET UNION,2–1,YUGOSLAVIA,4.0,A.E.T.
1,1964,SPAIN,SPAIN,2–1,SOVIET UNION,4.0,FULLTIME
2,1968,ITALY,ITALY,1–1,YUGOSLAVIA,4.0,"A.E.T. , 2–0 , REPLAY"
3,1972,BELGIUM,WEST GERMANY,3–0,SOVIET UNION,4.0,FULLTIME
4,1976,YUGOSLAVIA,CZECHOSLOVAKIA,2–2,WEST GERMANY,4.0,"A.E.T. , 5–3 PENALTIES"
5,1980,ITALY,WEST GERMANY,2–1,BELGIUM,8.0,FULLTIME
6,1984,FRANCE,FRANCE,2–0,SPAIN,8.0,FULLTIME
7,1988,WEST GERMANY,NETHERLANDS,2–0,SOVIET UNION,8.0,FULLTIME
8,1992,SWEDEN,DENMARK,2–0,GERMANY,8.0,FULLTIME
9,1996,ENGLAND,GERMANY,2–1,CZECH REPUBLIC,16.0,G.G.
10,2000,BELGIUM NETHERLANDS,FRANCE,2–1,ITALY,16.0,G.G.
11,2004,PORTUGAL,GREECE,1–0,PORTUGAL,16.0,FULLTIME
12,2008,AUSTRIA SWITZERLAND,SPAIN,1–0,GERMANY,16.0,FULLTIME
13,2012,POLAND UKRAINE,SPAIN,4–0,ITALY,16.0,FULLTIME
14,2016,FRANCE,PORTUGAL,1–0,FRANCE,24.0,A.E.T.
15,2020,EUROPE,ITALY,1–1,ENGLAND,24.0,"A.E.T. , 3–2 PENALTIES"
16,2024,GERMANY,SPAIN,2–1,ENGLAND,24.0,FULLTIME

In [107]:
def extract_each_goals(row):
  goals = row.split('–')
  return pd.Series([goals[0], goals[1]])
df[['Winner Goals', 'Runner Goals']] = df['Score'].astype(str).apply(extract_each_goals)

In [108]:
df.drop(columns=['Score'], inplace=True)

In [109]:
df.rename(columns={'Number of teams':'Teams'}, inplace=True)
df = df[['Year', 'Host',  'Teams','Winner', 'Winner Goals', 'Runner Goals',   'Hints' , 'Runner-up']]
df = df.astype(str).map(lambda x: x.capitalize())

In [110]:
df['Teams'] = df['Teams'].astype(float)
df['Teams'] = df['Teams'].astype('Int16')

In [111]:
df['Winner Goals'] = df['Winner Goals'].astype('int16')
df['Runner Goals'] = df['Runner Goals'].astype('int16')

In [112]:
df['Year'] = pd.to_datetime(df['Year']).dt.year

In [113]:
df

,Year,Host,Teams,Winner,Winner Goals,Runner Goals,Hints,Runner-up
0,1960,France,4,Soviet union,2,1,A.e.t.,Yugoslavia
1,1964,Spain,4,Spain,2,1,Fulltime,Soviet union
2,1968,Italy,4,Italy,1,1,"A.e.t. , 2–0 , replay",Yugoslavia
3,1972,Belgium,4,West germany,3,0,Fulltime,Soviet union
4,1976,Yugoslavia,4,Czechoslovakia,2,2,"A.e.t. , 5–3 penalties",West germany
5,1980,Italy,8,West germany,2,1,Fulltime,Belgium
6,1984,France,8,France,2,0,Fulltime,Spain
7,1988,West germany,8,Netherlands,2,0,Fulltime,Soviet union
8,1992,Sweden,8,Denmark,2,0,Fulltime,Germany
9,1996,England,16,Germany,2,1,G.g.,Czech republic
10,2000,Belgium netherlands,16,France,2,1,G.g.,Italy
11,2004,Portugal,16,Greece,1,0,Fulltime,Portugal
12,2008,Austria switzerland,16,Spain,1,0,Fulltime,Germany
13,2012,Poland ukraine,16,Spain,4,0,Fulltime,Italy
14,2016,France,24,Portugal,1,0,A.e.t.,France
15,2020,Europe,24,Italy,1,1,"A.e.t. , 3–2 penalties",England
16,2024,Germany,24,Spain,2,1,Fulltime,England

In [114]:
df.dtypes

Year             int32
Host            object
Teams            Int16
Winner          object
Winner Goals     int16
Runner Goals     int16
Hints           object
Runner-up       object
dtype: object

In [115]:
df.to_csv('_cleaned_overview.csv', index=False)